name = "SimplePWS"
uuid = "ee2b3880-206a-4a8c-b7d7-2bca105316e0"
authors = ["Manuel Reinhardt <manuel.jr16@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
